name: Release Please

on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
